### ISSUE TITLE
先导了happybase，再导入easybase会报错

### ISSUE THREAD

**Issue by lijc210** [wgzhao/easybase#5]
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import happybase
>>> import easybase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/miniconda3/envs/recommend/lib/python3.7/site-packages/easybase/__init__.py", line 17, in <module>
    from .connection import DEFAULT_HOST, DEFAULT_PORT, Connection
  File "/home/hadoop/miniconda3/envs/recommend/lib/python3.7/site-packages/easybase/connection.py", line 17, in <module>
    from Hbase_thrift import TTableName, TTimeRange, TColumnFamilyDescriptor, TTableDescriptor
ImportError: cannot import name 'TTableName' from 'Hbase_thrift' (unknown location)

**Comment by wgzhao** [comment]
收到，我尝试重现

**Comment by wgzhao** [comment]
@lijc210  错误已经重现，进行了修复，请更新到最新版 。https://github.com/wgzhao/easybase/releases
