### ISSUE TITLE
easybase==1.0.3无法正常import

### ISSUE THREAD

**Issue by shasky2014** [wgzhao/easybase#7]
```
easybase 1.0.3
thriftpy2 0.4.12

>>> import easybase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/easybase/__init__.py", line 12, in <module>
    module_name='HBase_thrift'
  File "/usr/local/lib64/python3.6/site-packages/thriftpy2/parser/__init__.py", line 33, in load
    include_dir=include_dir)
  File "/usr/local/lib64/python3.6/site-packages/thriftpy2/parser/parser.py", line 576, in parse
    with open(path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/easybase/HBase.thrift'
```

**Comment by shasky2014** [comment]
使用`easybase-1.0.2` 就ok的
```
Successfully installed easybase-1.0.2
sh-4.2# python3
>>> import easybase
>>>
```

**Comment by wgzhao** [comment]
大小写导致的问题

**Comment by wgzhao** [comment]
请卸载后，安装最新的版本

```
pip3 install easybase==1.0.5
```
